### ISSUE TITLE
(Not an issue, just a question) What problems does this plugin solve?

### ISSUE THREAD

**Issue by coopr** [rbang1/kong-plugin-aws-kinesis#1]
First, thanks for your contribution to the Kong community!

Second, I'd love some clarification on the utility of this plugin. What problems does it solve? Why not post data directly to Kinesis? How does routing data through Kong help?

Thanks!

**Comment by rbang1** [comment]
utilize other kong plugins, simplifies the request (e.g. hmac signing of request etc handled by this plugin), also for use cases where we do not want to expose aws creds to clients (e.g. browser requests)
